# Site settings
title: Apistevist
email: yt@apistevi.st
description: > # this means to ignore newlines until "baseurl:"
  A blog on Apistevism, under construction.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://apistevi.st" # the base hostname & protocol for your site
twitter_username: apistevism
github_username:  apistevist

# Build settings
markdown: kramdown
